USE [master]
GO

/****** Object:  Database [PROJECTPRJ301]    Script Date: 03/24/2022 00:43:36 ******/
CREATE DATABASE [PROJECTPRJ301] ON  PRIMARY 
( NAME = N'PROJECTPRJ301', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\PROJECTPRJ301.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PROJECTPRJ301_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\PROJECTPRJ301_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PROJECTPRJ301] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROJECTPRJ301].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PROJECTPRJ301] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET ARITHABORT OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PROJECTPRJ301] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PROJECTPRJ301] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PROJECTPRJ301] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PROJECTPRJ301] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PROJECTPRJ301] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PROJECTPRJ301] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PROJECTPRJ301] SET  READ_WRITE 
GO

ALTER DATABASE [PROJECTPRJ301] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PROJECTPRJ301] SET  MULTI_USER 
GO

ALTER DATABASE [PROJECTPRJ301] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PROJECTPRJ301] SET DB_CHAINING OFF 
GO

